spring.application.name=Persona

# Configuración de PostgreSQL (Render - Sistema de Pedidos)
spring.datasource.url=jdbc:postgresql://dpg-d6u7ei6uk2gs7397rcig-a.oregon-postgres.render.com/sistema_de_pedidos?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=jshhgsywy
spring.datasource.password=wdEbUdDfRnHGg2TQmOTqEpf3sZ4dI7fg
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
